---
- hosts: test
  become: yes

  pre_tasks:
    - name: updater apt
      become: true
      apt:
        upgrade: yes

    - name: Install dependencies for chrony.
      apt: 
        name: python3
        state: present

  tasks:
  - name: Ensure chrony (for time synchronization) is installed.
    dnf:
      name: chrony
      state: present

  - name: Ensure chrony is running.
    service:
      name: chronyd
      state: started
      enabled: yes

# The same as the above play, but in super-compact form!
- hosts: test
  become: yes
  tasks:
  - dnf: name=chrony state=present
  - service: name=chronyd state=started enabled=yes
